views/companies.py
from flask import Blueprint, render_template, flash, url_for, request, redirect
from flask_login import login_required, current_user

from database.database import get_db

bp = Blueprint('companies', __name__, url_prefix='/companies')


@bp.route('<record_id>', methods=['GET'])
def delete(record_id):
    db = get_db()

    try:
        deleted_id = db.execute("DELETE FROM partner WHERE id = ?", [record_id]).lastrowid
        db.commit()
    except db.Error as e:
        flash('There is some problem with database.', 'error')
        print('DB Error: ' + str(e))

    return redirect(url_for('companies.partner_list'))


@bp.get('/')
@login_required
def partner_list():
    db = get_db()
    items = []

    try:
        if current_user.role == "partner":
            items = db.execute(
                "SELECT partner.id, companyName, sector, "
                "strftime('%d-%m-%Y', datetime(created/1000, 'unixepoch')) as_string, u.firstName "
                "FROM partner JOIN user u ON u.id = partner.userId "
                "WHERE userId = ?", current_user.user_id
            ).fetchall()
        else:
            items = db.execute(
                "SELECT partner.id, companyName, sector, "
                "strftime('%d-%m-%Y', datetime(created/1000, 'unixepoch')) as_string, u.firstName "
                "FROM partner JOIN user u ON u.id = partner.userId"
            ).fetchall()
    except db.Error as e:
        flash('There is some problem with database.', 'error')
        print('DB Error: ' + str(e))

    return render_template('companies/companies.html', items=items)


@bp.get('/creation')
def creation():
    if current_user.role == "employee":
        return render_template('403.html')

    return render_template('companies/creation.html', data={})


@bp.post('/creation')
def create():
    db = get_db()
    data = request.form

    try:
        new_id = db.execute("INSERT INTO partner (userid, companyName, sector)  VALUES (?, ?, ?)",
                            (int(current_user.user_id), data['companyName'], data['sector'])
                            ).lastrowid
        db.commit()
        print('New item id: ' + str(new_id))

    except db.Error as e:
        flash('There is some problem with database.', 'error')
        print('DB Error: ' + str(e))

    return redirect(url_for('companies.partner_list'))

templates/companies/companies.html
{% extends "base.html" %}

{% block title %} Companies {% endblock %}

{% block content %}

    <h2>Companies</h2>

    {% if current_user.role != "employee" %}
        <a href={{ url_for('companies.creation') }}>
            <button id="create" type="submit" class="SignUpButton">Create Company</button>
        </a>
    {% endif %}

    <table id="companies">
        <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Sector</td>
            <td>Created</td>
            <td>Contact</td>
            {% if current_user.role != "employee" %}
                <td><a class="delete material-icons">delete</a></td>
            {% endif %}
        </tr>
        </thead>

        <tbody>
        {% if items | length == 0 %}
            <div>Žádné příspěvky.</div>
        {% else %}
            {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.companyName }}</td>
                    <td>{{ item.sector }}</td>
                    <td>{{ item.as_string }}</td>
                    <td>{{ item.firstName }}</td>
                    {% if current_user.role != "employee" %}
                        <td><a class="delete material-icons"
                               href={{ url_for('companies.delete', record_id = item.id) }}>delete</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>

    </table>

{% endblock %}

templates/companies/creation.html
{% extends "base.html" %}

{% block title %} Company creation {% endblock %}

{% block content %}

    <h2>Do you want to add a new partner?</h2>

    <form action="{{ url_for('companies.creation') }}" method="post">
        <div class="container">
            <label for="companyName"><b>Company Name</b></label>
            <input id="companyName" type="text" name="companyName" value="{{ data.companyName }}" required>

            <label for="sector"><b>Sector</b></label>
            <select name="sector" id="company" required>
                <option value="" selected disabled hidden>Choose here</option>
                <option value="engineering" {{ 'selected' if data.sector == 'engineering' }}>Engineering</option>
                <option value="finance" {{ 'selected' if data.sector == 'Finance' }}>Finance</option>
                <option value="agriculture" {{ 'selected' if data.sector == 'agriculture' }}>Agriculture</option>
                <option value="entertainment" {{ 'selected' if data.sector == 'entertainment' }}>Entertainment</option>
                <option value="other" {{ 'selected' if data.sector == 'Other' }}>Other</option>
            </select>

            <button type="submit" class="SignUpButton">Add New Company</button>
        </div>

    </form>

{% endblock %}