views/positions.py
from flask import Blueprint, render_template, flash, url_for, redirect, request
from flask_login import login_required, current_user

from database.database import get_db

bp = Blueprint('positions', __name__, url_prefix='/positions')


@bp.route('<record_id>', methods=['GET'])
def delete(record_id):
    db = get_db()

    try:
        id = db.execute("DELETE FROM position WHERE id = ?", [record_id]).lastrowid
        db.commit()
    except db.Error as e:
        flash('There is some problem with database.', 'error')
        print('DB Error: ' + str(e))

    return redirect(url_for('positions.position_list'))


@bp.get('/')
@login_required
def position_list():
    db = get_db()
    positions = []

    try:
        if current_user.role == "partner":
            positions = db.execute(
                "SELECT position.id, name, description, partner.companyName, partner.sector, "
                "user.firstName "
                "FROM position INNER JOIN partner ON position.partnerId = partner.id "
                "INNER JOIN user ON partner.userId = user.id "
                "WHERE userId = ?", current_user.user_id
            ).fetchall()
        else:
            positions = db.execute(
                "SELECT position.id, name, description, partner.companyName, partner.sector, "
                "user.firstName "
                "FROM position INNER JOIN partner ON position.partnerId = partner.id "
                "INNER JOIN user ON partner.userId = user.id"
            ).fetchall()
    except db.Error as e:
        flash('There is some problem with database.', 'error')
        print('DB Error: ' + str(e))

    return render_template('positions/positions.html', positions=positions)


@bp.get('/creation')
def creation():
    db = get_db()
    items = []

    if current_user.role == "employee":
        return render_template('403.html')

    try:
        items = db.execute(
            "SELECT id, companyName "
            "FROM partner"
        ).fetchall()
    except db.Error as e:
        flash('There is some problem with database.', 'error')
        print('DB Error: ' + str(e))

    return render_template('positions/creation.html', items=items, data={})


@bp.post('/creation')
def create():
    db = get_db()
    data = request.form

    try:
        partner_data = db.execute("SELECT id FROM partner WHERE companyName LIKE ?",
                                  ('%' + data['company'] + '%',)).fetchone()

        new_id = db.execute("INSERT INTO position (partnerId, name, description) "
                            "VALUES (?, ?, ?)",
                            (partner_data['id'], data['name'], data['description'])).lastrowid
        db.commit()
    except db.Error as e:
        flash('There is some problem with database.', 'error')
        print('DB Error: ' + str(e))

    return redirect(url_for('positions.position_list'))


@bp.route('/')
def introduction():
    return render_template('positions/positions.html', show_header=True)

templates/positions/creation.html
{% extends "base.html" %}

{% block title %} Creation {% endblock %}

{% block content %}
    <h2>Add new positions</h2>

    {% if error %}
        <div class="alert danger">
            {{ error }}
        </div>
    {% endif %}

    <form action="{{ url_for('positions.creation') }}" method="post">
        <div class="container">
            <label for="name"><b>Name</b></label>
            <input id="name" name="name" type="text" value="{{ data.name }}"
                   placeholder="Enter Position Name" required>

            <label for="description"><b>Description</b></label>
            <input id="description" name="description" type="text" value="{{ data.description }}"
                   placeholder="Enter Description"
                   required>

            <label for="company"><b>Company</b></label>

            <select name="company" id="company" required>
              <option value="" selected disabled hidden>Choose here</option>
                {% for item in items %}
                    <option value="{{ item.companyName }}" {{ 'selected' if data.company == item.companyName }}>{{ item.companyName }}</option>
                {% endfor %}
            </select>

            <button type="submit" class="SignUpButton">Create </button>
        </div>
    </form>
{% endblock %}

templates/positions/positions.html
{% extends "base.html" %}

{% block title %} Positions {% endblock %}

{% block content %}
    <h2>Positions</h2>

    {% if current_user.role != "employee" %}
        <a href={{ url_for('positions.creation') }}>
            <button id="create" type="submit" class="SignUpButton">Create Position</button>
        </a>
    {% endif %}

    <table id="companies">
        <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Description</td>
            <td>Company</td>
            <td>Sector</td>
            <td>Contact</td>
            {% if current_user.role != "employee" %}
                <td><a class="delete material-icons">delete</a></td>
            {% endif %}
        </tr>
        </thead>

        <tbody>
        {% if positions | length == 0 %}
            <div>No positions.</div>
        {% else %}
            {% for position in positions %}
                <tr>
                <td>{{ position.id }}</td>
                <td><div id = "left-text-align">{{ position.name }}</div></td>
                <td><div id = "left-text-align">{{ position.description }}</div></td>
                <td><a href={{ url_for('companies.partner_list') }}>{{ position.companyName }}</a></td>
                <td>{{ position.sector }}</td>
                <td>{{ position.firstName }}</td>
                {% if current_user.role != "employee" %}
                    <td><a class="delete material-icons"
                           href={{ url_for('positions.delete', record_id = position.id) }}>delete</a></td>
                {% endif %}
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>

    </table>

{% endblock %}